# -*- coding: utf-8 -*-
"""Smartvision_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8aXrLvnSic7UXxKMRaar8QVmjhOiMhC

STEP 10: STREAMLIT MULTI-PAGE APPLICATION
"""

pip install streamlit tensorflow ultralytics pandas numpy Pillow

"""
STEP 10: STREAMLIT MULTI-PAGE APPLICATION
-----------------------------------------
Run locally with:
    streamlit run Step10_streamlit_app.py

Expected file layout:
    Step10_streamlit_app.py
    models/
        VGG16_best.keras
        ResNet50_best.keras
        MobileNetV2_best.keras
        EfficientNetB0_best.keras
        yolo_best.pt
    results/
        classification_results.json
        model_comparison.png
        confusion_matrix.png
"""

import os
import json
import time
from io import BytesIO

import numpy as np
import pandas as pd
import streamlit as st
from PIL import Image

# ------------------------------ PAGE CONFIG ----------------------------------
st.set_page_config(page_title="SmartVision AI", page_icon="🔍", layout="wide")

CLASS_NAMES = [
    'airplane', 'bed', 'bench', 'bicycle', 'bird', 'bottle', 'bowl', 'bus',
    'cake', 'car', 'cat', 'chair', 'couch', 'cow', 'cup', 'dog', 'elephant',
    'horse', 'motorcycle', 'person', 'pizza', 'potted plant', 'stop sign',
    'traffic light', 'truck'
]


# ---------------------------- CACHED LOADERS ---------------------------------
@st.cache_resource
def load_cnn_models():
    """Load all 4 Keras classification models (if they exist)."""
    import tensorflow as tf
    model_files = {
        'VGG16':          'models/VGG16_best.keras',
        'ResNet50':       'models/ResNet50_best.keras',
        'MobileNetV2':    'models/MobileNetV2_best.keras',
        'EfficientNetB0': 'models/EfficientNetB0_best.keras',
    }
    return {name: tf.keras.models.load_model(path)
            for name, path in model_files.items() if os.path.exists(path)}


@st.cache_resource
def load_yolo_model():
    from ultralytics import YOLO
    path = 'models/yolo_best.pt' if os.path.exists('models/yolo_best.pt') else 'yolov8n.pt'
    return YOLO(path)


def preprocess(img: Image.Image, size: int = 224) -> np.ndarray:
    img = img.convert('RGB').resize((size, size))
    arr = np.asarray(img, dtype=np.float32) / 255.0
    return np.expand_dims(arr, 0)


# ---------------------------------- UI ---------------------------------------
st.sidebar.title("🔍 SmartVision AI")
page = st.sidebar.radio("Navigate", [
    "🏠 Home", "🏷️ Classification", "🎯 Object Detection",
    "📊 Model Performance", "ℹ️ About"
])

# ================================ HOME =======================================
if page == "🏠 Home":
    st.title("🔍 SmartVision AI")
    st.subheader("Intelligent Multi-Class Object Recognition System")
    st.write("""
    SmartVision AI is a comprehensive computer-vision platform that combines
    **transfer-learning image classification** with **YOLOv8 object detection**
    across 25 real-world categories from the COCO dataset.
    """)
    c1, c2, c3 = st.columns(3)
    c1.metric("Classes", "25")
    c2.metric("Models", "5 (4 CNN + YOLOv8)")
    c3.metric("Dataset", "2,500 images")

    st.markdown("### Supported Classes")
    st.write(", ".join(CLASS_NAMES))

    st.markdown("### How to Use")
    st.markdown("""
    1. Go to **Classification** to identify a single object in an image.
    2. Go to **Object Detection** to locate multiple objects at once.
    3. Compare model performance in the **Model Performance** tab.
    """)

# ============================ CLASSIFICATION =================================
elif page == "🏷️ Classification":
    st.title("🏷️ Image Classification")
    st.write("Upload an image — all 4 CNN models will predict the object class.")

    up = st.file_uploader("Upload image", type=["jpg", "jpeg", "png"])
    if up:
        img = Image.open(up)
        col1, col2 = st.columns([1, 1.3])
        col1.image(img, caption="Uploaded image", use_column_width=True)

        with st.spinner("Loading models & predicting..."):
            models = load_cnn_models()
            if not models:
                st.error("No classification models found in `models/`.")
            else:
                x = preprocess(img)
                rows = []
                for name, m in models.items():
                    t0 = time.time()
                    probs = m.predict(x, verbose=0)[0]
                    dt = (time.time() - t0) * 1000
                    top5 = probs.argsort()[-5:][::-1]
                    rows.append({
                        'Model': name,
                        'Prediction': CLASS_NAMES[top5[0]],
                        'Confidence': f"{probs[top5[0]]*100:.1f}%",
                        'Top-5': ", ".join(CLASS_NAMES[i] for i in top5),
                        'Time (ms)': f"{dt:.1f}",
                    })
                col2.dataframe(pd.DataFrame(rows), hide_index=True, use_container_width=True)

# =========================== OBJECT DETECTION ================================
elif page == "🎯 Object Detection":
    st.title("🎯 Object Detection (YOLOv8)")
    conf = st.slider("Confidence threshold", 0.1, 0.95, 0.4, 0.05)
    up = st.file_uploader("Upload image", type=["jpg", "jpeg", "png"])
    if up:
        img = Image.open(up).convert('RGB')
        with st.spinner("Running detection..."):
            model = load_yolo_model()
            t0 = time.time()
            res = model.predict(np.array(img), conf=conf, verbose=False)[0]
            dt = (time.time() - t0) * 1000

        col1, col2 = st.columns([1.4, 1])
        col1.image(res.plot()[:, :, ::-1], caption=f"Detections (inference {dt:.1f} ms)")

        if len(res.boxes):
            rows = []
            for b in res.boxes:
                cid = int(b.cls[0])
                rows.append({
                    'Class': res.names.get(cid, str(cid)),
                    'Confidence': f"{float(b.conf[0])*100:.1f}%",
                    'BBox [x1,y1,x2,y2]': [int(v) for v in b.xyxy[0].tolist()],
                })
            col2.dataframe(pd.DataFrame(rows), hide_index=True, use_container_width=True)
        else:
            col2.info("No objects detected. Try lowering the threshold.")

# ========================== MODEL PERFORMANCE ================================
elif page == "📊 Model Performance":
    st.title("📊 Model Performance Dashboard")

    if os.path.exists('results/classification_results.json'):
        results = json.load(open('results/classification_results.json'))
        df = pd.DataFrame([{k: v for k, v in r.items() if k != 'history'} for r in results])
        st.dataframe(df, hide_index=True, use_container_width=True)

        c1, c2 = st.columns(2)
        c1.bar_chart(df.set_index('model')['test_accuracy'])
        c2.bar_chart(df.set_index('model')['inference_ms'])
    else:
        st.warning("Run Step 8 training to generate `results/classification_results.json`.")

    if os.path.exists('results/model_comparison.png'):
        st.image('results/model_comparison.png', caption='Model comparison')
    if os.path.exists('results/confusion_matrix.png'):
        st.image('results/confusion_matrix.png', caption='Confusion matrix (best model)')

# ================================= ABOUT =====================================
else:
    st.title("ℹ️ About SmartVision AI")
    st.markdown("""
    **Project:** SmartVision AI — Intelligent Multi-Class Object Recognition System
    **Dataset:** 25-class subset of COCO (2,500 images)
    **Models:** VGG16, ResNet50, MobileNetV2, EfficientNetB0, YOLOv8
    **Stack:** TensorFlow/Keras, Ultralytics YOLOv8, Streamlit, Hugging Face Spaces
    **Author:** Megha
    """)